---
title: "SynergyFinder2 ZIP and Loewe with different curve fitting methods"
author: "Shuyu Zheng"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r include=FALSE}
library(tidyverse)
```
# Mean value for all combo cells

Loewe score with LOESS curve fitting method causes an error

```{r echo=FALSE}
tableZIPLoewe <- readxl::read_xlsx("./result_ZIP_2021-01-07_LOESS.xlsx") %>% 
  rename(ZIP_LOESS = Synergy)
for (i in c("ZIP", "Loewe")){
  for (j in c("LM", "LL4")){
    tmp <- readxl::read_xlsx(paste0("result_", i, "_2021-01-07_", j, ".xlsx")) %>% 
      dplyr::select("PairIndex", "Conc1", "Conc2", Synergy)
    colnames(tmp)[which(colnames(tmp) == "Synergy")] <- paste(i, j, sep="_")
    tableZIPLoewe <- dplyr::left_join(tableZIPLoewe, tmp, by =c("PairIndex", "Conc1", "Conc2"))
  }
}
tableZIPLoewe <- tableZIPLoewe %>% 
  mutate(group = paste(PairIndex, Conc1, Conc2, sep = "_")) 
tableZIPLoewe <- tableZIPLoewe %>% 
  filter(Conc1 != 0 & Conc2 != 0)
knitr::kable(t(apply(dplyr::select(tableZIPLoewe, ZIP_LL4, ZIP_LM, ZIP_LOESS, Loewe_LL4, Loewe_LM), 2, mean)))
```

## ZIP

```{r echo=FALSE}
tableZIP <- tableZIPLoewe %>% 
  dplyr::select(group, ZIP_LM, ZIP_LL4, ZIP_LOESS) %>% 
  gather(key = curve_fitting, value = synergy, ZIP_LM, ZIP_LL4, ZIP_LOESS) %>% 
  mutate(fitting = sub("ZIP_", "", curve_fitting))
p <- ggplot(data = filter(tableZIP), mapping = aes(x = group, y = synergy, color = factor(fitting)))  +
  geom_vline(aes(xintercept = group), alpha = 1, size = 0.1) +
  geom_point(size = 0.3) + 
  labs(x = "Block-conc1-conc2", color = "curve fitting") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position="bottom")
p
```
```{r echo=FALSE}
ggsave("ZIP_diff_fitting.png", plot = p, device = "png",dpi = 600, width = 10, height = 2)
```
```{r echo=FALSE}
knitr::kable(cor(dplyr::select(tableZIPLoewe, ZIP_LM, ZIP_LL4, ZIP_LOESS)))
```

## Loewe

Loewe score with LOESS curve fitting method causes an error

```{r echo=FALSE}
plot(tableZIPLoewe$Loewe_LL4, tableZIPLoewe$Loewe_LM, xlab = "LL4", ylab = "LM")
```

```{r echo=FALSE}
cor.test(tableZIPLoewe$Loewe_LL4, tableZIPLoewe$Loewe_LM)
```
