# Copyright Shuyu Zheng and Jing Tang - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Shuyu Zheng <shuyu.zheng@helsinki.fi>, March 2021
#
# SynergyFinder
#
# Functions on this page:
#
# PlotDoseResponse: Visualize the Drug Combination Dose-response Data

#' Visualize the Drug Combination Dose-response Data
#'
#' A function to visualize the drug combination dose-response data
#'
#' @param data A list object generated by function \code{\link{ReshapeData}}.
#' @param block_ids A vector of characters/integers or NULL. It contains the
#'   block IDs for the blocks to visualize. By default, it is NULL so that the
#'   visualization of all the drug combinations in input \code{data}.
#' @param drugs A vector of characters or integers with length of 2. It contains
#'   the index for two drugs to plot. For example, \code{c(1, 2)} indicates to
#'   plot "drug1" and "drug2" in the input \code{data}.
#' @param adjusted A logical value. If it is \code{FALSE}, original response
#'   matrix will be plotted. If it is \code{TRUE}, adjusted response matrix will
#'   be plotted.
#' @param statistic A character or NULL. It indicates the statistics printed
#'   in the plot while there are replicates in input data. Available values are:
#'   \itemize{
#'     \item \strong{sem} Standard error of mean;
#'     \item \strong{ci} 95% confidence interval.
#'   }
#'   If it is \code{NULL}, no statistics will be printed.
#' @param summary_statistic A vector of characters or NULL. It indicates the
#'   summary statistics printed in heatmap for all the \code{plot_value} in
#'   whole combination matrix. Available values are:
#'   \itemize{
#'     \item \strong{mean} Median value for all the responses or synergy
#'     scores in the matrix;
#'     \item \strong{median} Median value for all the responses or synergy
#'     scores in the matrix;
#'     \item \strong{quantile_90} 90% quantile. User could change the number to
#'     print different sample quantile. For example quantile_50 equal to median. 
#'   }
#'   If it is \code{NULL}, no statistics will be printed.
#' @param high_value_color An R color value. It indicates the color for the
#'   high values.
#' @param low_value_color An R color value. It indicates the color for low
#'   values.
#' @param point_color An R color value. It indicates the color for points in
#'   dose response curve plots.
#' @param curve_color An R color value. It indicates the color for curves in 
#'   dose response curve plots.
#' @param Emin A numeric or \code{NA}. the minimal effect of the drug used in
#'   the 4-parameter log-logistic function to fit the dose-response curve. If
#'   it is not NA, it is fixed the value assigned by the user. Default setting
#'   is \code{NA}.
#' @param Emax A numeric or \code{NA}. the maximal effect of the drug used in
#'   the 4-parameter log-logistic function to fit the dose-response curve. If
#'   it is not NA, it is fixed the value assigned by the user. Default setting
#'   is \code{NA}.
#' @param save_file A parameter to specify if the visualization results are
#'   saved as pdf files in current working directory or not. If it is FALSE,
#'   the results are returned as a list of the plots. It is FALSE by default.
#' @param file_type A character. It indicates the format of files you want to
#'   save as. Default is "pdf". Available values are "jpeg", "bmp", "png",
#'   "tiff", "pdf", "svg".
#' @param file_name A character vector. It indicates the file names, if
#'   user chose to save the plot to local directory.If it is not defined by
#'   user, a default name will be assigned.
#' @param width a numeric value. It indicates the width of saved file.
#' @param height a numeric value. It indicates the height of saved file.
#'
#' @return A list of plot objects recorded by \link[grDevices]{recordPlot}. The 
#'   plot will be saved into a local file if \code{save.file = TRUE}. If 
#'   \code{save.file = FALSE}, the plot will be printed in default graphic
#'   device.
#'
#' @author
#'   \itemize{
#'     \item Liye He \email{liye.he@helsinki.fi},
#'     \item Shuyu Zheng \email{shuyu.zheng@helsinki.fi}
#'   }
#' @import ggplot2
#' @export
#'
#' @examples
#' \dontrun{
#' data("mathews_screening_data")
#' data <- ReshapeData(mathews_screening_data)
#' plots <- PlotDoseResponse(data)
#' }
PlotDoseResponse <- function(data,
                             block_ids = NULL,
                             drugs = c(1, 2),
                             adjusted = TRUE,
                             statistic = NULL,
                             summary_statistic = "mean",
                             high_value_color = "#A90217",
                             low_value_color = "#2166AC",
                             point_color = "#C24B40",
                             curve_color = "black", 
                             Emin = NA,
                             Emax = NA,
                             save_file = FALSE,
                             file_type = "pdf",
                             file_name = NULL,
                             width = 12,
                             height = 6) {
  # 1. Check the input data
  if (!is.list(data)) {
    stop("Input data is not in list format!")
  }
  if (!all(c("drug_pairs", "response") %in% names(data))) {
    stop("Input data should contain at least tow elements: 'drug_pairs' and 
         'response'. Please prepare your data with 'ReshapeData' function.")
  }
  
  # 2. Select the dose response table for plotting.
  if (adjusted) {
    plot_value = "response"
  } else {
    plot_value = "response_origin"
  }

  # 3. Select block
  if (!is.null(block_ids)) {
    no_block_id <- setdiff(block_ids, data$drug_pairs$block_id)
    if (length(no_block_id) > 0) {
      stop(
        "Selected block_ids ",
        paste(unique(no_block_id), sep = ", "),
        " are not found in the input data. Please check the input data."
      )
    }
  } else {
    block_ids <- data$drug_pairs$block_id
  }
  
  plots <- vector(mode = "list", length = length(block_ids))
  names(plots) <- block_ids

  i <- 1
  for (b in block_ids) {

    # ggplot object for heatmap
    dose_response_plot <- Plot2DrugHeatmap(
      data,
      plot_block = b,
      drugs = drugs,
      plot_value = plot_value,
      statistic = statistic,
      summary_statistic = summary_statistic,
      high_value_color = high_value_color,
      low_value_color = low_value_color
    )
    
    # plot dose response curve

    graphics::plot.new()
    graphics::layout(matrix(c(1, 3, 2, 3), 2, 2, byrow = TRUE))

    for (i in drugs){
      PlotDoseResponseCurve(
        data,
        plot_block = b,
        drug_index = i,
        plot_setting = list(
          mgp = c(2, 0.5, 0),
          font.main = 2,
          cex.main = 1 / 12 * 13.5,
          cex.sub = 1
        ),
        grid = grid,
        point_color = point_color,
        curve_color = curve_color,
        Emin = Emin,
        Emax = Emax
      )
    }
    # vps <- baseViewports()
    # pushViewport()
    print(dose_response_plot, vp = grid::viewport(
      height = grid::unit(1, "npc"),
      width = grid::unit(0.5, "npc"),
      just = c("left", "top"),
      y = 1, x = 0.5
    ))
    # popViewport()
    merge_plot <- grDevices::recordPlot()

    plots[[b]] <- merge_plot
    if (save_file) {
      if (is.null(file_name)) {
        if (adjusted) {
          file <- paste(
            data$drug_pairs[which(data$drug_pairs$block_id == b), 
                            paste0("drug", drugs)],
            "adjusted_dose_response_block",
            b,
            sep = "_"
          )
        } else {
          file <- paste(
            data$drug_pairs[which(data$drug_pairs$block_id == b), 
                            paste0("drug", drugs)],
            "original_dose_response_block",
            b,
            sep = "_"
          )
        }
      } else {
        file <- file_name[i]
        i <- i + 1
      }

      if (!file_type %in% c("jpeg", "bmp", "png", "tiff", "pdf", "svg")) {
        warning(
          "Can not save plot in ", file_type, " format. Avaliable formats are ",
          "'svg', 'jpeg', 'bmp', 'png', 'tiff', and 'pdf'.")
      } else if (file_type == "pdf") {
        grDevices::pdf(paste(file, file_type, sep = "."),
          width = width, height = height
        )
      } else if (file_type == "svg") {
        grDevices::svg(paste(file, file_type, sep = "."),
          width = width, height = height
        )
      } else {
        do.call(file_type, args = list(
          filename = paste(file, file_type, sep = "."),
          width = width, height = height,
          units = "in", res = 600
        ))
      }
      #
      # grDevices::jpeg(file_name, width = 800, height = 600)
      grDevices::replayPlot(merge_plot)
      grDevices::dev.off()
    } else {
      grDevices::dev.new(noRStudioGD = TRUE)
      grDevices::replayPlot(plots[[b]])
      grDevices::dev.off()
    }
  }
  return(plots)
}